module.exports =
  errorCodes:
    '701': 'Niederdruckstörung - Bitte Inst. rufen'
    '702': 'Niederdrucksperre - RESET automatisch'
    '703': 'Frostschutz - Bitte Inst. rufen'
    '704': 'Heissgasstörung - Reset in hh:mm'
    '705': 'Motorschutz VEN - Bitte Inst. rufen'
    '706': 'Motorschutz BSUP - Bitte Inst. rufen'
    '707': 'Codierung WP - Bitte Inst. rufen'
    '708': 'Fühler Rücklauf - Bitte Inst. rufen'
    '709': 'Fühler Vorlauf - Bitte Inst. rufen'
    '710': 'Fühler Heissgas - Bitte Inst. rufen'
    '711': 'Fühler Aussentemp. - Bitte Inst. rufen'
    '712': 'Fühler Warmwasser - Bitte Inst. rufen'
    '713': 'Fühler WQ-Ein - Bitte Inst. rufen'
    '714': 'Heissgas WW - Reset in hh:mm'
    '715': 'Hochdruck-Abschalt. - RESET automatisch'
    '716': 'Hochdruckstörung - Bitte Inst rufen'
    '717': 'Durchfluss-WQ - Bitte Inst. rufen'
    '718': 'Max. Aussentemp. - RESET automatisch'
    '719': 'Min. Aussentemp. - RESET automatisch'
    '720': 'WQ-Temperatur - RESET automatisch in hh:mm'
    '721': 'Niederdruckabschaltung - RESET automatisch'
    '722': 'Tempdiff Heizwasser - Bitte Inst. rufen'
    '723': 'Tempdiff Warmwasser - Bitte Inst. rufen'
    '724': 'Tempdiff Abtauen - Bitte Inst. rufen'
    '725': 'Anlagefehler WW - Bitte Inst. rufen'
    '726': 'Fühler Mischkreis 1 - Bitte Inst. rufen'
    '727': 'Soledruck - Bitte Inst. rufen'
    '728': 'Fühler WQ-Aus - Bitte Inst. rufen'
    '729': 'Drehfeldfehler - Bitte Inst. rufen'
    '730': 'Leistung Ausheizen - Bitte Inst. rufen'
    '732': 'Störung Kühlung - Bitte Inst. rufen'
    '733': 'Störung Anode - Bitte Inst. rufen'
    '734': 'Störung Anode - Bitte Inst. rufen'
    '735': 'Fühler Ext. Energiequelle - Bitte Inst. rufen'
    '736': 'Fühler Solarkollektor - Bitte Inst. rufen'
    '737': 'Fühler Solarspeicher - Bitte Inst. rufen'
    '738': 'Fühler Mischkreis2 - Bitte Inst. rufen'
    '750': 'Fühler Rücklauf extern - Bitte Inst. rufen'
    '751': 'Phasenüberwachungsfehler'
    '752': 'Phasenüberwachungs / Durchflussfehler'
    '755': 'Verbindung zu Slave verloren - Bitte Inst. rufen'
    '756': 'Verbindung zu Master verloren - Bitte Inst. rufen'
    '757': 'ND-Störung bei WW-Gerät'
    '758': 'Störung Abtauung'
    '759': 'Meldung TDI'
    '760': 'Störung Abtauung'
    '761': 'LIN-Verbindung unterbrochen'
    '762': 'Fühler Ansaug-Verdichter'
    '763': 'Fühler Ansaug-Verdampfer'
    '764': 'Fühler Verdichterheizung'
    '765': 'Überhitzung'
    '766': 'Einsatzgrenzen-VD'
    '767': 'STB E-Stab'
    '770': 'Niedrige Überhitzung'
    '771': 'Hohe Überhitzung'
    '776': 'Einsatzgrenzen-VD'
    '777': 'Expansionsventil'
    '778': 'Fühler Niederdruck'
    '779': 'Fühler Hochdruck'
    '780': 'Fühler EVI'
    '781': 'Fühler Flüssig, vor Ex-Ventil'
    '782': 'Fühler EVI Sauggas'
    '783': 'Kommunikation SEC-Inverter'
    '784': 'VSS gesperrt'
    '785': 'SEC-Board defekt'
    '786': 'Kommunikation SEC-Inverter'
    '787': 'VD Alarm'
    '788': 'Schwerw. Inverter Fehler'
    '789': 'LIN/Kodierung nicht vorhanden'
    '790': 'Schwerw. Inverter Fehler'
    '791': 'ModBus Verbindung verloren'
    '792': 'LIN-Verbindung unterbrochen'
    '793': 'Schwerw. Inverter Fehler'